* KanBan - Sprint 2

|       | to do           | on going | test | done |
|-------+-----------------+----------+------+------|
| All   |                 |          |      |      |
| US#7  | [T1 T2] [T15]   |          |      |      |
| US#8  | [T3 T4] [T16]   |          |      |      |
| US#9  | [T5 T6] [T17]   |          |      |      |
| US#10 | [T7 T8] [T18]   |          |      |      |
| US#11 | [T9 T10] [T19]  |          |      |      |
| US#12 | [T11 T12] [T20] |          |      |      |
| US#13 | [T13 T14] [T21] |          |      |      |


**** Liste des tâches
+ T1 : MySql : ajouterProjet(#infos), modifierProjet(id_pro, #infos), supprimerProjet(id_pro), 
+ T2 : Web : page de modification d’un projet (formulaireProjet.php) et actions ajout/suppression
+ T15 : Test E2E US#7

+ T3 : MySql : listerDevs(), selectionnerScrumMaster(id_pro, id_dev), selectionnerProductOwner(id_pro, id_dev), selectionnerDev(id_pro, id_dev)
+ T4 : Web : liste de développeurs (menu déroulant ou non, à cocher ou non, sélection multiple ou non …) dans la page formulaireProjet.php
+ T16 : Test E2E US#8

+ T5 : MySql : listerUS(id_pro)
+ T6 : Web : page backlog.php (mise en page du tableau)
+ T17 : Test E2E US#9

+ T7 : MySql : ajouterUS(#infos), modifierUS(id_us, #infos), supprimerUS(id_us)
+ T8 : Web : page de modification d’une US (formulaireUS.php) et actions ajout/suppression
+ T18 : Test E2E US#10

+ T9 : MySql : modifierPrioriteUS(id_us, priorite)
+ T10 : Web : pour un PO connecté : modification de la prio dans la page formulaireUS.php
+ T19 : Test E2E US#11

+ T11 : MySql : listerSprint(id_pro), infosSprint(id_sprint)
+ T12 : Web : pages listeSprints.php et sprint.php
+ T20 : Test E2E US#12

+ T13 : MySql : ajouterSprint(#infos), modifierSprint(id_sprint, #infos), supprimerSprint(id_sprint)
+ T14 : Web : page de modification d’un sprint (formulaireSprint.php) et actions ajout/suppression
+ T21 : Test E2E US#13


**** User Stories
Projet
+ US#7 : En tant que développeur je souhaite ajouter/éditer/supprimer mon projet.
+ US#8 : En tant que développeur je souhaite sélectionner/retirer des développeurs à mon projet et identifier un Scrum Master et un Product Owner.
Baklog
+ US#9 : En tant que visiteur/développeur je souhaite visualiser le backlog d’un projet.
+ US#10 : En tant que développeur je souhaite ajouter/éditer/supprimer une User Story d’un projet auquel je suis associé.
+ US#11 : En tant que Product Owner, je souhaite modifier la priorité des User Stories de mes projets. 
Sprint
+ US#12 : En tant que visiteur/développeur je souhaite avoir une vue générale sur les sprints d’un projet et une vue spécifique sur un sprint.
+ US#13 : En tant que développeur je souhaite ajouter/éditer/supprimer un sprint dans un projet auquel je suis associé.